# Example file for controlling loading image and overlay text display
# To activate remove "_example" from filename
# ---------------------------------------------------------------------------------------
# Note: Specify filenames without extension (.jpg will be added internally)
# ---------------------------------------------------------------------------------------

# Overlay title
Title: <b><#0077FF>Reforged Eden 1.10</color></b> <size=65%><#ffffff>(build 60)</color></size>

# Overlay body (typically multi-line text)
# If commented out, only the title will be displayed
Body: |
  <size=135%><#ffffff><b>Sep 12 Major Update: War and Industry</b></color></size>
  <size=85%>•<indent=3%>Overhauled Trading Station sectors.</indent>
  •<indent=3%>Overhauled orbital trading factories.</indent>
  •<indent=3%>Added decorative decals for trading POIs.</indent>
  •<indent=3%>Added ambient cargo shuttle traffic.</indent>
  •<indent=3%>Updated secure supply caches.</indent>
  •<indent=3%>Added new combat and mining sites.</indent> (PDA update needed)
  •<indent=3%>Added new decorative asteroid fields and sector nebula.</indent>
  •<indent=3%>Added wind and geothermal power.</indent>
  •<indent=3%>Added alarm sentry.</indent>
  •<indent=3%>Added new star classes.</indent>
  •<indent=3%>Lowered volume and frequency of radio chatter.</indent>
  •<indent=3%>Updated POIs.</indent>
  •<indent=3%>Updated Empyriopedia.</indent>
  •<indent=3%>Many, many other updates and fixes. See full change notes on the Steam Workshop.</indent>
  <#ffff00>This update requires the <#ffffff>pda readdata</color> command for <u>existing</u> single player saves to get the updated PDA. A new game is recommended for the best experience but <i>not required</i>.</color></size>
  
# To show a certain image at the start of each loading image sequence, specify the respective file name
# To use the default random image selection, comment out the following line
FirstPic: p49

# To show the overlay text with certain images only, specify the respective file names
# To show the text with every image, comment out the following line
# ShowWith: [ p02, p03 ]

# Show time for images - if not specified differently below
# If commented out, the default is 10 seconds
# Note: This time depends on the speed of the client computer as when loading a game a lot of work is done in parallel
StandardShowTime: 15

# To set a specific show time for certain images, specify "filename: time" lines
# If not needed, comment out all lines of the following parameter
ShowTimes:
  p49: 45
  # p06: 8
